[package]
name = "parallel_downloader"
version = "0.1.2"
edition = "2021"

[dependencies]
ureq = "2.9.6"
structopt = "0.3.26"
regex = "1.10.3"
log = "0.4.21"
env_logger = "0.11.3"
log4rs = "1.3.0"
anyhow = "1.0.96"
url = "2.5.4"
